enum Status {
  HOMEWORK,
  CLASSTEST,
  ATTENDANCEDETAILS,
  CLASSTIMETABLE,
  CIRCULAR,
  EVENT,
  NEWS,
  SMS,
  VOICE,
  STAFFDETAILS,
  VEHICLETRACKING,
  FEEPAYMENT,
  FEEINVOICE,
  FEEPENDING,
  EXAMRESULT,
  EXAMTIMETABLE,
  LIVECLASSES,
  STUDYLAB,
  BARROWLIST,
  RENEWLIST,
  FINELIST,
  FINEINVOICE,
  MATERIALBILL,
  MATERIALBILLISSUED,
  EXTRACURRICULAR,
  REFRESHMENT,
  SCHOOLCALENDER,
  DEFAULT
}

enum LoadingType { stable,loading, loaded, completed, error }

